/**
 * AUTO-GENERATED — do not edit by hand.
 * Source: src/app/core/api/openapi.json  (local copy of atlas-gateway/openapi.json)
 *
 * Sync step: whenever atlas-gateway/openapi.json changes, copy it here and re-run:
 *   cp ../atlas-gateway/openapi.json src/app/core/api/openapi.json
 *   npm run gen:api
 *
 * Generated by openapi-typescript@7.13.0
 */
/* eslint-disable @typescript-eslint/consistent-indexed-object-style */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Completions */
        post: operations["chat_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Embeddings */
        post: operations["embeddings_v1_embeddings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatCompletionRequest */
        ChatCompletionRequest: {
            /** Max Tokens */
            max_tokens?: number | null;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Model */
            model: string;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /** Temperature */
            temperature?: number | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /** EmbeddingData */
        EmbeddingData: {
            /** Embedding */
            embedding: number[];
            /** Index */
            index: number;
            /**
             * Object
             * @default embedding
             */
            object: string;
        };
        /** EmbeddingRequest */
        EmbeddingRequest: {
            /** Input */
            input: string | string[];
            /** Model */
            model: string;
        };
        /** EmbeddingResponse */
        EmbeddingResponse: {
            /** Data */
            data: components["schemas"]["EmbeddingData"][];
            /** Model */
            model: string;
            /**
             * Object
             * @default list
             */
            object: string;
            usage: components["schemas"]["EmbeddingUsage"];
        };
        /** EmbeddingUsage */
        EmbeddingUsage: {
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Model */
        Model: {
            /** Id */
            id: string;
            /**
             * Object
             * @default model
             */
            object: string;
            /** Owned By */
            owned_by: string;
        };
        /** ModelList */
        ModelList: {
            /** Data */
            data: components["schemas"]["Model"][];
            /**
             * Object
             * @default list
             */
            object: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    chat_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    embeddings_v1_embeddings_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbeddingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
